name: 'Upload website to AWS S3'
on: [push,pull_request]

jobs:
  Upload-websie-to-s3:
    runs-on: ubuntu-latest
    steps:
      - name: '1: Checkout'
        uses: actions/checkout@v3
        
      - name: '2: Show directory'
        run: ls
      
      - name: '3: Connect to AWS and upload files to S3'
        uses: ochanje210/s3-upload-action@master
        with:
          AWS_ACCESS_KEY_ID:     ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_S3_BUCKET:         ${{secrets.AWS_S3_BUCKET}}
          SOURCE_DIR:            ./*
          DEST_DIR:              ${{secrets.AWS_S3_BUCKET}}
